package model;
// Generated 11-Dec-2018 10:36:16 by Hibernate Tools 5.3.0.Beta2

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Carte generated by hbm2java
 */
public class Carte implements java.io.Serializable {

	private BigDecimal id;
	private String nomPoint;
	private String latitude;
	private String longitude;
	private BigDecimal type;
	private BigDecimal statute;
	private Set connections = new HashSet(0);
	private Set missions = new HashSet(0);
	private Set equipes = new HashSet(0);

	public Carte() {
	}

	public Carte(BigDecimal id, String nomPoint, String latitude, String longitude, BigDecimal type,
			BigDecimal statute) {
		this.id = id;
		this.nomPoint = nomPoint;
		this.latitude = latitude;
		this.longitude = longitude;
		this.type = type;
		this.statute = statute;
	}

	public Carte(BigDecimal id, String nomPoint, String latitude, String longitude, BigDecimal type, BigDecimal statute,
			Set connections, Set missions, Set equipes) {
		this.id = id;
		this.nomPoint = nomPoint;
		this.latitude = latitude;
		this.longitude = longitude;
		this.type = type;
		this.statute = statute;
		this.connections = connections;
		this.missions = missions;
		this.equipes = equipes;
	}

	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	public String getNomPoint() {
		return this.nomPoint;
	}

	public void setNomPoint(String nomPoint) {
		this.nomPoint = nomPoint;
	}

	public String getLatitude() {
		return this.latitude;
	}

	public void setLatitude(String latitude) {
		this.latitude = latitude;
	}

	public String getLongitude() {
		return this.longitude;
	}

	public void setLongitude(String longitude) {
		this.longitude = longitude;
	}

	public BigDecimal getType() {
		return this.type;
	}

	public void setType(BigDecimal type) {
		this.type = type;
	}

	public BigDecimal getStatute() {
		return this.statute;
	}

	public void setStatute(BigDecimal statute) {
		this.statute = statute;
	}

	public Set getConnections() {
		return this.connections;
	}

	public void setConnections(Set connections) {
		this.connections = connections;
	}

	public Set getMissions() {
		return this.missions;
	}

	public void setMissions(Set missions) {
		this.missions = missions;
	}

	public Set getEquipes() {
		return this.equipes;
	}

	public void setEquipes(Set equipes) {
		this.equipes = equipes;
	}

}
