package model;
// Generated 11-Dec-2018 10:36:16 by Hibernate Tools 5.3.0.Beta2

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Equipe generated by hbm2java
 */
public class Equipe implements java.io.Serializable {

	private BigDecimal id;
	private Carte carte;
	private Mission mission;
	private String type;
	private Set membreses = new HashSet(0);

	public Equipe() {
	}

	public Equipe(BigDecimal id, Carte carte, Mission mission, String type) {
		this.id = id;
		this.carte = carte;
		this.mission = mission;
		this.type = type;
	}

	public Equipe(BigDecimal id, Carte carte, Mission mission, String type, Set membreses) {
		this.id = id;
		this.carte = carte;
		this.mission = mission;
		this.type = type;
		this.membreses = membreses;
	}

	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	public Carte getCarte() {
		return this.carte;
	}

	public void setCarte(Carte carte) {
		this.carte = carte;
	}

	public Mission getMission() {
		return this.mission;
	}

	public void setMission(Mission mission) {
		this.mission = mission;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public Set getMembreses() {
		return this.membreses;
	}

	public void setMembreses(Set membreses) {
		this.membreses = membreses;
	}

}
