package model;
// Generated 11-Dec-2018 10:36:16 by Hibernate Tools 5.3.0.Beta2

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Management generated by hbm2java
 */
public class Management implements java.io.Serializable {

	private BigDecimal id;
	private String spe;
	private Set connections = new HashSet(0);
	private Set profils = new HashSet(0);

	public Management() {
	}

	public Management(BigDecimal id) {
		this.id = id;
	}

	public Management(BigDecimal id, String spe, Set connections, Set profils) {
		this.id = id;
		this.spe = spe;
		this.connections = connections;
		this.profils = profils;
	}

	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	public String getSpe() {
		return this.spe;
	}

	public void setSpe(String spe) {
		this.spe = spe;
	}

	public Set getConnections() {
		return this.connections;
	}

	public void setConnections(Set connections) {
		this.connections = connections;
	}

	public Set getProfils() {
		return this.profils;
	}

	public void setProfils(Set profils) {
		this.profils = profils;
	}

}
