package model;
// Generated 11-Dec-2018 10:36:16 by Hibernate Tools 5.3.0.Beta2

import java.math.BigDecimal;
import java.util.Date;

/**
 * Membres generated by hbm2java
 */
public class Membres implements java.io.Serializable {

	private BigDecimal id;
	private Mission missionByEquipeMissionCarteId;
	private Mission missionByEquipeMissionId;
	private Equipe equipe;
	private String nom;
	private Date prenom;

	public Membres() {
	}

	public Membres(BigDecimal id, Mission missionByEquipeMissionCarteId, Mission missionByEquipeMissionId,
			Equipe equipe, String nom, Date prenom) {
		this.id = id;
		this.missionByEquipeMissionCarteId = missionByEquipeMissionCarteId;
		this.missionByEquipeMissionId = missionByEquipeMissionId;
		this.equipe = equipe;
		this.nom = nom;
		this.prenom = prenom;
	}

	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	public Mission getMissionByEquipeMissionCarteId() {
		return this.missionByEquipeMissionCarteId;
	}

	public void setMissionByEquipeMissionCarteId(Mission missionByEquipeMissionCarteId) {
		this.missionByEquipeMissionCarteId = missionByEquipeMissionCarteId;
	}

	public Mission getMissionByEquipeMissionId() {
		return this.missionByEquipeMissionId;
	}

	public void setMissionByEquipeMissionId(Mission missionByEquipeMissionId) {
		this.missionByEquipeMissionId = missionByEquipeMissionId;
	}

	public Equipe getEquipe() {
		return this.equipe;
	}

	public void setEquipe(Equipe equipe) {
		this.equipe = equipe;
	}

	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	public Date getPrenom() {
		return this.prenom;
	}

	public void setPrenom(Date prenom) {
		this.prenom = prenom;
	}

}
