package model;
// Generated 11-Dec-2018 10:36:16 by Hibernate Tools 5.3.0.Beta2

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Mission generated by hbm2java
 */
public class Mission implements java.io.Serializable {

	private BigDecimal id;
	private Carte carte;
	private String lieu;
	private Date debut;
	private Date fin;
	private short nbDePlaces;
	private Boolean flagFin;
	private Set equipes = new HashSet(0);
	private Set membresesForEquipeMissionCarteId = new HashSet(0);
	private Set connections = new HashSet(0);
	private Set membresesForEquipeMissionId = new HashSet(0);

	public Mission() {
	}

	public Mission(BigDecimal id, Carte carte, String lieu, Date debut, Date fin, short nbDePlaces) {
		this.id = id;
		this.carte = carte;
		this.lieu = lieu;
		this.debut = debut;
		this.fin = fin;
		this.nbDePlaces = nbDePlaces;
	}

	public Mission(BigDecimal id, Carte carte, String lieu, Date debut, Date fin, short nbDePlaces, Boolean flagFin,
			Set equipes, Set membresesForEquipeMissionCarteId, Set connections, Set membresesForEquipeMissionId) {
		this.id = id;
		this.carte = carte;
		this.lieu = lieu;
		this.debut = debut;
		this.fin = fin;
		this.nbDePlaces = nbDePlaces;
		this.flagFin = flagFin;
		this.equipes = equipes;
		this.membresesForEquipeMissionCarteId = membresesForEquipeMissionCarteId;
		this.connections = connections;
		this.membresesForEquipeMissionId = membresesForEquipeMissionId;
	}

	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	public Carte getCarte() {
		return this.carte;
	}

	public void setCarte(Carte carte) {
		this.carte = carte;
	}

	public String getLieu() {
		return this.lieu;
	}

	public void setLieu(String lieu) {
		this.lieu = lieu;
	}

	public Date getDebut() {
		return this.debut;
	}

	public void setDebut(Date debut) {
		this.debut = debut;
	}

	public Date getFin() {
		return this.fin;
	}

	public void setFin(Date fin) {
		this.fin = fin;
	}

	public short getNbDePlaces() {
		return this.nbDePlaces;
	}

	public void setNbDePlaces(short nbDePlaces) {
		this.nbDePlaces = nbDePlaces;
	}

	public Boolean getFlagFin() {
		return this.flagFin;
	}

	public void setFlagFin(Boolean flagFin) {
		this.flagFin = flagFin;
	}

	public Set getEquipes() {
		return this.equipes;
	}

	public void setEquipes(Set equipes) {
		this.equipes = equipes;
	}

	public Set getMembresesForEquipeMissionCarteId() {
		return this.membresesForEquipeMissionCarteId;
	}

	public void setMembresesForEquipeMissionCarteId(Set membresesForEquipeMissionCarteId) {
		this.membresesForEquipeMissionCarteId = membresesForEquipeMissionCarteId;
	}

	public Set getConnections() {
		return this.connections;
	}

	public void setConnections(Set connections) {
		this.connections = connections;
	}

	public Set getMembresesForEquipeMissionId() {
		return this.membresesForEquipeMissionId;
	}

	public void setMembresesForEquipeMissionId(Set membresesForEquipeMissionId) {
		this.membresesForEquipeMissionId = membresesForEquipeMissionId;
	}

}
