package model;
// Generated 11-Dec-2018 10:36:16 by Hibernate Tools 5.3.0.Beta2

import java.math.BigDecimal;

/**
 * Parametre generated by hbm2java
 */
public class Parametre implements java.io.Serializable {

	private BigDecimal id;
	private Boolean modeNuit;
	private Boolean notificationMail;

	public Parametre() {
	}

	public Parametre(BigDecimal id) {
		this.id = id;
	}

	public Parametre(BigDecimal id, Boolean modeNuit, Boolean notificationMail) {
		this.id = id;
		this.modeNuit = modeNuit;
		this.notificationMail = notificationMail;
	}

	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	public Boolean getModeNuit() {
		return this.modeNuit;
	}

	public void setModeNuit(Boolean modeNuit) {
		this.modeNuit = modeNuit;
	}

	public Boolean getNotificationMail() {
		return this.notificationMail;
	}

	public void setNotificationMail(Boolean notificationMail) {
		this.notificationMail = notificationMail;
	}

}
