package model;
// Generated 11-Dec-2018 10:36:16 by Hibernate Tools 5.3.0.Beta2

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Profil generated by hbm2java
 */
public class Profil implements java.io.Serializable {

	private BigDecimal id;
	private Management management;
	private RescueSearch rescueSearch;
	private Medical medical;
	private Logistic logistic;
	private String nom;
	private String prenom;
	private String numeroDeTelephone;
	private String role;
	private Date dateDeNaissance;
	private Set connections = new HashSet(0);

	public Profil() {
	}

	public Profil(BigDecimal id, Management management, RescueSearch rescueSearch, Medical medical, Logistic logistic,
			String nom, String prenom, String numeroDeTelephone, String role) {
		this.id = id;
		this.management = management;
		this.rescueSearch = rescueSearch;
		this.medical = medical;
		this.logistic = logistic;
		this.nom = nom;
		this.prenom = prenom;
		this.numeroDeTelephone = numeroDeTelephone;
		this.role = role;
	}

	public Profil(BigDecimal id, Management management, RescueSearch rescueSearch, Medical medical, Logistic logistic,
			String nom, String prenom, String numeroDeTelephone, String role, Date dateDeNaissance, Set connections) {
		this.id = id;
		this.management = management;
		this.rescueSearch = rescueSearch;
		this.medical = medical;
		this.logistic = logistic;
		this.nom = nom;
		this.prenom = prenom;
		this.numeroDeTelephone = numeroDeTelephone;
		this.role = role;
		this.dateDeNaissance = dateDeNaissance;
		this.connections = connections;
	}

	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	public Management getManagement() {
		return this.management;
	}

	public void setManagement(Management management) {
		this.management = management;
	}

	public RescueSearch getRescueSearch() {
		return this.rescueSearch;
	}

	public void setRescueSearch(RescueSearch rescueSearch) {
		this.rescueSearch = rescueSearch;
	}

	public Medical getMedical() {
		return this.medical;
	}

	public void setMedical(Medical medical) {
		this.medical = medical;
	}

	public Logistic getLogistic() {
		return this.logistic;
	}

	public void setLogistic(Logistic logistic) {
		this.logistic = logistic;
	}

	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	public String getPrenom() {
		return this.prenom;
	}

	public void setPrenom(String prenom) {
		this.prenom = prenom;
	}

	public String getNumeroDeTelephone() {
		return this.numeroDeTelephone;
	}

	public void setNumeroDeTelephone(String numeroDeTelephone) {
		this.numeroDeTelephone = numeroDeTelephone;
	}

	public String getRole() {
		return this.role;
	}

	public void setRole(String role) {
		this.role = role;
	}

	public Date getDateDeNaissance() {
		return this.dateDeNaissance;
	}

	public void setDateDeNaissance(Date dateDeNaissance) {
		this.dateDeNaissance = dateDeNaissance;
	}

	public Set getConnections() {
		return this.connections;
	}

	public void setConnections(Set connections) {
		this.connections = connections;
	}

}
