package fr.eisti.cergy.jee.model;
// Generated 22 nov. 2016 03:13:26 by Hibernate Tools 4.3.5.Final

 import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Mission generated by hbm2java
 */
@Entity
@Table(name = "MISSION")
public class Mission implements java.io.Serializable {

	private Long  idMission;
	private String debutMission;
	private String finMission;
	private String lieuMission;
	private Long placeMission;


	public Mission() {
	}

	public Mission(Long  idMission) {
		this.idMission = idMission;
	}

	public Mission(Long  idMission, String debutMission, String finMission, String lieuMission, Long placeMission) {
		this.idMission = idMission;
		this.debutMission = debutMission;
		this.finMission = finMission;
		this.lieuMission = lieuMission;
		this.placeMission = placeMission;
	}

	@Id

	@Column(name = "ID_Mission", unique = true, nullable = false, scale = 0)
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator="MISSION_gen_seq")
    @SequenceGenerator(name="MISSION_gen_seq", sequenceName="SEQ_ID_MISSION", allocationSize=1)

	public Long  getIdMission() {
		return this.idMission;
	}

	public void setIdMission(Long  idMission) {
		this.idMission = idMission;
	}

	@Column(name = "DATE_DEBUT", length = 20)
	public String getdebutMission() {
		return this.debutMission;
	}

	public void setdebutMission(String debutMission) {
		this.debutMission = debutMission;
	}

	@Column(name = "DATE_FIN", length = 70)
	public String getfinMission() {
		return this.finMission;
	}

	public void setfinMission(String finMission) {
		this.finMission = finMission;
	}

	@Column(name = "LIEU", length = 70)
	public String getLieuMission() {
		return this.lieuMission;
	}

	public void setLieuMission(String lieuMission) {
		this.lieuMission = lieuMission;
	}

	@Column(name = "PLACE", length = 4)
	public Long getPlaceMission() {
		return this.placeMission;
	}

	public void setPlaceMission(Long placeMission) {
		this.placeMission = placeMission;
	}






}
