DROP TABLE pompier;
DROP TABLE mission;


DROP SEQUENCE SEQ_ID_POMPIER;
DROP SEQUENCE SEQ_ID_MISSION;

CREATE TABLE pompier(
id_pompier NUMBER(19,0) NOT NULL ENABLE PRIMARY KEY ,
nom VARCHAR(30) NOT NULL ENABLE ,
prenom VARCHAR(30) NOT NULL ENABLE,
age NUMBER(2) NOT NULL ENABLE
);

CREATE TABLE mission(
id_mission NUMBER(19,0) NOT NULL ENABLE,
date_debut VARCHAR2(50) NOT NULL ENABLE,
date_fin varchar2(50) NOT NULL ENABLE,
lieu VARCHAR(30) NOT NULL ENABLE,
place number(19,0) NOT NULL ENABLE,
PRIMARY KEY (id_mission)
);

CREATE SEQUENCE seq_id_pompier START WITH 1;
CREATE SEQUENCE seq_id_mission START WITH 1;

commit;